In [1]:
import torch

In [3]:
zero=torch.zeros(size=(4,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
org_ten=torch.tensor([[1,2,3],[4,5,6]])
org_ten

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
resh=org_ten.reshape(3,2)

In [6]:
resh

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [8]:
vieww=org_ten.view(3,2)
vieww

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [17]:
org_ten1=torch.tensor(5)
org_ten2=torch.tensor(6)
sta=torch.stack([org_ten1,org_ten2])
sta


tensor([5, 6])

In [19]:
original_tensor = torch.tensor([[[1], [2], [3]]])
squeezed_tensor = original_tensor.squeeze()
squeezed_tensor


tensor([1, 2, 3])

In [23]:
original_tensor2 = torch.tensor([1, 2, 3])
unsqueezed_tensor = original_tensor2.unsqueeze(dim=0)
unsqueezed_tensor

tensor([[1, 2, 3]])

In [53]:
org_ten3=torch.tensor([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
t=torch.permute(org_ten3,(1,0))
t

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6],
        [7, 7]])

In [54]:
org_ten[1,2]

tensor(6)

In [55]:
org_ten[1,1]=88
org_ten

tensor([[ 1,  2,  3],
        [ 4, 88,  6]])

In [56]:
org_ten[0,:]

tensor([1, 2, 3])

In [57]:
org_ten[:,1]

tensor([ 2, 88])

In [58]:
org_ten[0:1,1:2]

tensor([[2]])

In [59]:
import numpy as np
x=np.array([1,2,3])
x


array([1, 2, 3])

In [60]:
tn=torch.from_numpy(x)
tn

tensor([1, 2, 3])

In [61]:
y=tn.numpy()
y

array([1, 2, 3])

In [62]:
rt=torch.rand(size=(7,7))
rt

tensor([[0.8642, 0.5288, 0.3795, 0.1392, 0.9887, 0.4075, 0.2220],
        [0.2656, 0.4600, 0.2872, 0.4473, 0.6073, 0.9989, 0.2170],
        [0.5673, 0.9263, 0.3216, 0.3760, 0.9691, 0.4381, 0.5463],
        [0.0143, 0.8329, 0.9714, 0.6727, 0.0946, 0.4694, 0.8946],
        [0.0298, 0.6977, 0.8834, 0.0672, 0.4378, 0.7427, 0.4250],
        [0.0089, 0.8275, 0.9036, 0.8910, 0.1941, 0.8347, 0.6161],
        [0.1735, 0.5637, 0.0067, 0.7620, 0.7791, 0.7093, 0.0260]])

In [63]:
rt2=torch.rand(size=(1,7))

In [70]:
rt3=torch.permute(rt2,(1,0))
mat=torch.matmul(rt,rt3)
mat

tensor([[1.8322],
        [1.8369],
        [2.2471],
        [2.2366],
        [1.8923],
        [2.4340],
        [1.5829]])

In [74]:
rrt=torch.rand(size=(2,3))
rrt2=torch.rand(size=(2,3))
rrt3=torch.permute(rrt2,(1,0))
mat1=torch.matmul(rrt,rrt3)
mat1

tensor([[0.7177, 0.5386],
        [0.6061, 0.4516]])

In [75]:
torch.max(mat1)

tensor(0.7177)

In [76]:
torch.min(mat1)

tensor(0.4516)

In [77]:
torch.argmax(mat1)

tensor(0)

In [78]:
torch.argmin(mat1)

tensor(3)

In [83]:
torch.manual_seed(7)

In [84]:
z=torch.rand(size=(1,1,1,10))
zx=z.squeeze()


In [85]:
z

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [86]:
z.shape

torch.Size([1, 1, 1, 10])

In [87]:
zx

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

In [88]:
zx.shape

torch.Size([10])